# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIChallenge

  pod 'Kingfisher', '~> 7.6.1'
  pod 'RealmSwift', '~> 10'

  target 'SwiftUIChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUIChallengeUITests' do
    # Pods for testing
  end

end
